# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

group = eu.minemania
mod_id = mobcountmod
mod_name = MobCountMod
author = Annevdl29
mod_file_name = mobcountmod-fabric
project_slug = mobcountmod
modrinth_debug = false

#Current and version
mod_version = 1.9.11

#Required malilib version
malilib_version = 0.22.7
malilib_mod_version = >=0.22.7

# Minecraft, Fabric and mappings versions
minecraft_version_malilib = 1.21.3
minecraft_version_mod = 1.21.3
minecraft_version = 1.21.3
minecraft_version_dependency = >=1.21.2 <=1.21.3
mappings_version = 1.21.3+build.2

fabric_loader_version = 0.16.14
mod_menu_version = 12.0.0